// morph Design Intelligence Database — component pattern library.
//
// Renders a content model extracted from an arbitrary site into a complete,
// production-grade landing page using a design profile. The output is a
// single self-contained HTML document plus a generated design-system
// stylesheet (morph-theme.css).

import { componentStyles, renderCatalogSections, renderHeroSplit, renderHeroBento, renderHeroEditorial, renderHeroMinimal, renderIconRowFeatures } from "./components.js";
import {
  footerVariantStyles,
  heroAnimationStyles,
  mobileNavStyles,
  navVariantStyles,
  pageScripts,
  profileBackdropHtml,
  profileBackdropStyles,
  renderSiteFooter,
  renderSiteNav,
  resolveFooterVariant,
  resolveNavVariant,
  spotlightStyles
} from "./site-chrome.js";
import { tasteRenderFlags } from "./taste.js";

const TYPE_TOKENS = `
  --text-xs: 12px;
  --text-sm: 13px;
  --text-md: 15px;
  --text-base: 16px;
  --text-lg: 17px;
  --text-xl: 20px;
  --text-2xl: clamp(28px, 4vw, 40px);
  --text-3xl: clamp(28px, 4.5vw, 44px);
  --text-display: clamp(40px, 7vw, 76px);
  --text-quote: clamp(22px, 3.4vw, 34px);
`;

export function renderStylesheet(profile, options = {}) {
  const { colors, fonts, radius, shadows } = profile;
  const flags = options.renderFlags ?? tasteRenderFlags(options.taste ?? {});
  const texture = textureLayer(profile);
  const extra = options.includeComponents !== false ? componentStyles(profile) : "";
  const revealMs = flags.revealDurationMs || 0;
  const hoverLift = flags.hoverLift ?? "-2px";
  const sectionScale = flags.sectionPaddingScale ?? 1;
  const sectionPad = sectionScale === 1
    ? "clamp(var(--space-8), 9vw, var(--space-9))"
    : `clamp(${Math.round((72 * sectionScale) / 4) * 4}px, 9vw, ${Math.round((120 * sectionScale) / 4) * 4}px)`;

  const raw = `/* ${profile.name} — generated by morph from its design intelligence database.
   Inspired by: ${profile.inspiration}${options.referenceInspiration ? `\n   Active references: ${options.referenceInspiration}` : ""} */

:root {
  --bg: ${colors.bg};
  --bg-alt: ${colors.bgAlt};
  --surface: ${colors.surface};
  --surface-raised: ${colors.surfaceRaised};
  --border: ${colors.border};
  --border-strong: ${colors.borderStrong};
  --ink: ${colors.ink};
  --ink-secondary: ${colors.inkSecondary};
  --muted: ${colors.muted};
  --primary: ${colors.primary};
  --primary-hover: ${colors.primaryHover};
  --primary-ink: ${colors.primaryInk};
  --accent: ${colors.accent};
  --focus: ${colors.focus};

  --font-display: ${fonts.displayStack};
  --font-body: ${fonts.bodyStack};
  --font-mono: ${fonts.monoStack};

  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-xl: ${radius.xl};
  --radius-pill: ${radius.pill};

  --shadow-card: ${shadows.card};
  --shadow-raised: ${shadows.raised};
  --shadow-button: ${shadows.button};

  --space-1: 4px;  --space-2: 8px;  --space-3: 12px;  --space-4: 16px;
  --space-5: 24px; --space-6: 32px; --space-7: 48px; --space-8: 64px;
  --space-9: 96px; --space-10: 128px;

  --container: 1120px;
${TYPE_TOKENS}

  /* Emil Kowalski motion tokens — ease-out for UI, ease-in-out for movement */
  --ease-out: cubic-bezier(0.23, 1, 0.32, 1);
  --ease-in-out: cubic-bezier(0.77, 0, 0.175, 1);
  --ease-hover: cubic-bezier(0.25, 0.46, 0.45, 0.94);
  --duration-fast: 160ms;
  --duration-ui: 220ms;
}

*, *::before, *::after { box-sizing: border-box; }
* { margin: 0; }

html { scroll-behavior: smooth; }
@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  *, *::before, *::after { animation: none !important; transition: none !important; }
}

body {
  background: var(--bg);
  color: var(--ink);
  font-family: var(--font-body);
  font-size: var(--text-base);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

img, svg { display: block; max-width: 100%; }

::selection { background: var(--primary); color: var(--primary-ink); }

a { color: inherit; text-decoration: none; }

:focus-visible {
  outline: 2px solid var(--focus);
  outline-offset: 3px;
  border-radius: var(--radius-sm);
}

.container {
  width: min(var(--container), 100% - 48px);
  margin-inline: auto;
}

/* ── Navigation ─────────────────────────────────────────────────────────── */

.site-nav {
  position: sticky;
  top: 0;
  z-index: 50;
  backdrop-filter: blur(16px) saturate(1.4);
  -webkit-backdrop-filter: blur(16px) saturate(1.4);
  background: color-mix(in srgb, var(--bg) 78%, transparent);
  border-bottom: 1px solid var(--border);
}
.site-nav .container {
  display: flex;
  align-items: center;
  gap: var(--space-6);
  height: 64px;
}
.brand {
  display: flex;
  align-items: center;
  gap: 10px;
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: 17px;
  letter-spacing: ${fonts.displayTracking};
}
.brand-mark {
  width: 26px; height: 26px;
  border-radius: 8px;
  background: var(--primary);
  flex: none;
}
.nav-links {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin-left: auto;
  list-style: none;
  padding: 0;
}
.nav-links a {
  padding: 8px 14px;
  border-radius: var(--radius-pill);
  font-size: 14px;
  font-weight: 500;
  color: var(--muted);
  transition: color var(--duration-fast) var(--ease-hover), background var(--duration-fast) var(--ease-hover);
}
.nav-links a:hover { color: var(--ink); background: color-mix(in srgb, var(--ink) 7%, transparent); }
.nav-cta { margin-left: var(--space-3); }

/* ── Buttons ────────────────────────────────────────────────────────────── */

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  border-radius: var(--radius-pill);
  border: 1px solid transparent;
  font-family: var(--font-body);
  font-size: 15px;
  font-weight: 600;
  line-height: 1;
  cursor: pointer;
  white-space: nowrap;
  transition: transform var(--duration-fast) var(--ease-out),
              box-shadow var(--duration-fast) var(--ease-out),
              background var(--duration-fast) var(--ease-out),
              border-color var(--duration-fast) var(--ease-out);
}
.btn:active { transform: translateY(1px) scale(0.98); transition-duration: 100ms; }

.btn-primary {
  background: ${colors.buttonGradient};
  color: var(--primary-ink);
  box-shadow: var(--shadow-button);
}
.btn-primary:hover {
  transform: translateY(-1px);
  box-shadow: var(--shadow-button);
}

.btn-ghost {
  background: transparent;
  color: var(--ink);
  border-color: var(--border-strong);
}
.btn-ghost:hover {
  border-color: var(--primary);
  background: color-mix(in srgb, var(--primary) 8%, transparent);
}

.btn-lg { padding: 15px 30px; font-size: 16px; }

/* ── Hero ───────────────────────────────────────────────────────────────── */

.hero {
  position: relative;
  overflow: hidden;
  padding: clamp(88px, 14vw, 160px) 0 clamp(72px, 10vw, 120px);
  text-align: center;
}
${colors.glow !== "none" ? `.hero::before {
  content: "";
  position: absolute;
  inset: 0;
  background: ${colors.glow};
  pointer-events: none;
}` : ""}
${texture}
.hero .container { position: relative; }

.eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 7px 16px;
  border-radius: var(--radius-pill);
  border: 1px solid var(--border-strong);
  background: color-mix(in srgb, var(--surface) 65%, transparent);
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.02em;
  color: var(--ink-secondary);
  margin-bottom: var(--space-6);
}
.eyebrow::before {
  content: "";
  width: 7px; height: 7px;
  border-radius: 50%;
  background: var(--primary);
  box-shadow: 0 0 10px var(--primary);
}

.hero h1 {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(40px, 7vw, 76px);
  line-height: 1.04;
  letter-spacing: ${fonts.displayTracking};
  max-width: 17ch;
  margin-inline: auto;
  text-wrap: balance;
}
.hero h1 .accent { color: var(--primary); }

.hero .lede {
  margin: var(--space-6) auto 0;
  max-width: 58ch;
  font-size: clamp(17px, 2vw, 20px);
  line-height: 1.65;
  color: var(--muted);
  text-wrap: pretty;
}

.hero-ctas {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: var(--space-4);
  margin-top: var(--space-7);
}

/* ── Stats strip ────────────────────────────────────────────────────────── */

.stats {
  border-block: 1px solid var(--border);
  background: var(--bg-alt);
}
.stats .container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: var(--space-6);
  padding: var(--space-7) 0;
  text-align: center;
}
.stat-value {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4vw, 40px);
  letter-spacing: ${fonts.displayTracking};
  color: var(--ink);
}
.stat-label {
  margin-top: 6px;
  font-size: 14px;
  color: var(--muted);
}

/* ── Sections ───────────────────────────────────────────────────────────── */

.section { padding: ${sectionPad} 0; }
.section.alt { background: var(--bg-alt); border-block: 1px solid var(--border); }

.section-head {
  max-width: 640px;
  margin-bottom: var(--space-8);
}
.section-head.centered { margin-inline: auto; text-align: center; }
.section-head .kicker {
  font-family: var(--font-mono);
  font-size: 13px;
  font-weight: 500;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--primary);
  margin-bottom: var(--space-3);
}
.section-head h2 {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4.5vw, 44px);
  line-height: 1.12;
  letter-spacing: ${fonts.displayTracking};
  text-wrap: balance;
}
.section-head p {
  margin-top: var(--space-4);
  font-size: 17px;
  color: var(--muted);
  text-wrap: pretty;
}

/* ── Feature cards ──────────────────────────────────────────────────────── */

.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: var(--space-5);
}
.card {
  position: relative;
  padding: var(--space-6);
  border-radius: var(--radius-lg);
  border: 1px solid var(--border);
  background: var(--surface);
  box-shadow: var(--shadow-card);
  transition: transform var(--duration-ui) var(--ease-out),
              border-color var(--duration-ui) var(--ease-out),
              box-shadow var(--duration-ui) var(--ease-out);
}
.card:hover {
  transform: translateY(${hoverLift});
  border-color: ${colors.cardHoverBorder};
  box-shadow: var(--shadow-raised);
}
.card-accent {
  width: 3px;
  height: 28px;
  border-radius: 999px;
  background: var(--primary);
  margin-bottom: var(--space-4);
}
.card h3 {
  font-family: var(--font-display);
  font-size: 19px;
  font-weight: 600;
  letter-spacing: -0.01em;
  margin-bottom: var(--space-3);
}
.card p { font-size: 15px; line-height: 1.65; color: var(--muted); }

/* ── Prose / detail sections ────────────────────────────────────────────── */

.split {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: var(--space-8);
  align-items: center;
}
.split .panel {
  border-radius: var(--radius-xl);
  border: 1px solid var(--border);
  background: var(--surface);
  box-shadow: var(--shadow-card);
  padding: var(--space-7);
  min-height: 240px;
  display: grid;
  place-items: center;
}
.split .split-visual {
  overflow: hidden;
  padding: 0;
  min-height: 280px;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border);
  background: var(--surface);
  box-shadow: var(--shadow-card);
}
.split .split-mesh {
  width: 100%;
  height: 100%;
  min-height: 280px;
  background:
    radial-gradient(ellipse 80% 60% at 20% 20%, color-mix(in srgb, var(--primary) 28%, transparent), transparent 70%),
    radial-gradient(ellipse 70% 50% at 80% 80%, color-mix(in srgb, var(--accent) 18%, transparent), transparent 65%),
    linear-gradient(145deg, var(--bg-alt), var(--surface));
}
.split .panel .glyph {
  font-family: var(--font-display);
  font-size: 64px;
  font-weight: ${fonts.displayWeight};
  color: var(--primary);
}
.split h3 {
  font-family: var(--font-display);
  font-size: clamp(24px, 3vw, 32px);
  font-weight: ${fonts.displayWeight};
  letter-spacing: ${fonts.displayTracking};
  line-height: 1.15;
  margin-bottom: var(--space-4);
  text-wrap: balance;
}
.split p { color: var(--muted); font-size: 16.5px; text-wrap: pretty; }
.split ul {
  margin-top: var(--space-5);
  padding: 0;
  list-style: none;
  display: grid;
  gap: var(--space-3);
}
.split li {
  display: flex;
  gap: 12px;
  align-items: baseline;
  font-size: 15.5px;
  color: var(--ink-secondary);
}
.split li::before {
  content: "→";
  color: var(--primary);
  font-weight: 700;
  flex: none;
}

/* ── Quote band ─────────────────────────────────────────────────────────── */

.quote-band { text-align: center; }
.quote-band blockquote {
  font-family: var(--font-display);
  font-size: clamp(22px, 3.4vw, 34px);
  font-weight: 500;
  line-height: 1.35;
  letter-spacing: -0.01em;
  max-width: 26ch;
  margin-inline: auto;
  text-wrap: balance;
}
.quote-band cite {
  display: block;
  margin-top: var(--space-5);
  font-style: normal;
  font-size: 15px;
  color: var(--muted);
}

/* ── CTA band ───────────────────────────────────────────────────────────── */

.cta-band { padding: clamp(72px, 9vw, 110px) 0; }
.cta-band .inner {
  position: relative;
  overflow: hidden;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border-strong);
  background: var(--surface);
  box-shadow: var(--shadow-raised);
  padding: clamp(48px, 7vw, 88px) var(--space-6);
  text-align: center;
}
.cta-band .inner::before {
  content: "";
  position: absolute;
  inset: 0;
  background: ${colors.glow === "none"
    ? `linear-gradient(180deg, color-mix(in srgb, var(--primary) 6%, transparent), transparent)`
    : colors.glow};
  pointer-events: none;
}
.cta-band h2 {
  position: relative;
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4.5vw, 44px);
  letter-spacing: ${fonts.displayTracking};
  line-height: 1.1;
  max-width: 20ch;
  margin-inline: auto;
  text-wrap: balance;
}
.cta-band p {
  position: relative;
  margin: var(--space-4) auto 0;
  max-width: 52ch;
  color: var(--muted);
  font-size: 17px;
}
.cta-band .hero-ctas { position: relative; }

/* ── Footer ─────────────────────────────────────────────────────────────── */

.site-footer {
  border-top: 1px solid var(--border);
  background: var(--bg-alt);
  padding: var(--space-8) 0 var(--space-7);
}
.site-footer .top {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-6);
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-6);
}
.footer-links {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-2);
  list-style: none;
  padding: 0;
}
.footer-links a {
  padding: 6px 12px;
  border-radius: var(--radius-pill);
  font-size: 14px;
  color: var(--muted);
  transition: color var(--duration-fast) var(--ease-hover);
}
.footer-links a:hover { color: var(--ink); }
.site-footer .legal {
  font-size: 13.5px;
  color: var(--muted);
  border-top: 1px solid var(--border);
  padding-top: var(--space-5);
}

/* ── Reveal-on-scroll ───────────────────────────────────────────────────── */

.reveal {
  opacity: ${revealMs > 0 ? "0" : "1"};
  transform: ${revealMs > 0 ? "translateY(14px)" : "none"};
  transition: opacity ${revealMs}ms var(--ease-out), transform ${revealMs}ms var(--ease-out);
}
.reveal.in { opacity: 1; transform: none; }
@media (prefers-reduced-motion: reduce) {
  .reveal { opacity: 1; transform: none; }
}

/* ── Responsive ─────────────────────────────────────────────────────────── */

.preserved-content .prose-block p {
  color: var(--ink-secondary);
  font-size: 17px;
  line-height: 1.75;
  max-width: 68ch;
  margin: 0 auto var(--space-5);
}
.preserved-content .table-wrap {
  overflow-x: auto;
  margin: var(--space-6) auto;
  max-width: 100%;
}
.preserved-content table {
  width: 100%;
  border-collapse: collapse;
  font-size: 15px;
}
.preserved-content td {
  border: 1px solid var(--border);
  padding: 10px 14px;
  color: var(--ink-secondary);
}

@media (max-width: 720px) {
  .nav-links { display: none; }
  .hero-ctas .btn { width: 100%; max-width: 340px; }
  .site-nav .container { gap: var(--space-4); }
}
${profileBackdropStyles(profile, flags)}
${heroAnimationStyles(flags)}
${navVariantStyles(options.navVariant ?? "glass", profile)}
${mobileNavStyles()}
${footerVariantStyles()}
${flags.showSpotlight ? spotlightStyles() : ""}
${extra}
`;
  return tokenizeGeneratedCss(raw);
}

const SPACING_TOKEN_MAP = [
  ["128px", "var(--space-10)"],
  ["96px", "var(--space-9)"],
  ["64px", "var(--space-8)"],
  ["48px", "var(--space-7)"],
  ["32px", "var(--space-6)"],
  ["24px", "var(--space-5)"],
  ["16px", "var(--space-4)"],
  ["12px", "var(--space-3)"],
  ["8px", "var(--space-2)"],
  ["4px", "var(--space-1)"]
];

const FONT_TOKEN_MAP = [
  ["17px", "var(--text-lg)"],
  ["16px", "var(--text-base)"],
  ["15px", "var(--text-md)"],
  ["14px", "var(--text-sm)"],
  ["13px", "var(--text-sm)"],
  ["18px", "var(--text-lg)"],
  ["20px", "var(--text-xl)"]
];

function tokenizeGeneratedCss(css) {
  let out = String(css);
  for (const [literal, token] of SPACING_TOKEN_MAP) {
    out = out.replaceAll(` ${literal};`, ` ${token};`);
    out = out.replaceAll(` ${literal})`, ` ${token})`);
    out = out.replaceAll(`: ${literal};`, `: ${token};`);
    out = out.replaceAll(`: ${literal})`, `: ${token})`);
    out = out.replaceAll(`gap: ${literal}`, `gap: ${token}`);
    out = out.replaceAll(`padding: ${literal}`, `padding: ${token}`);
    out = out.replaceAll(`margin: ${literal}`, `margin: ${token}`);
  }
  for (const [literal, token] of FONT_TOKEN_MAP) {
    out = out.replaceAll(`font-size: ${literal}`, `font-size: ${token}`);
  }
  return out;
}

function textureLayer(profile) {
  const line = profile.mode === "dark" ? "rgba(255,255,255,0.04)" : "rgba(15,23,42,0.04)";
  if (profile.texture === "grid" || profile.texture === "dots") {
    return `.hero::after {
  content: "";
  position: absolute;
  inset: 0;
  background-image: radial-gradient(${line} 1px, transparent 1px);
  background-size: 28px 28px;
  mask-image: radial-gradient(ellipse 70% 60% at 50% 0%, black 30%, transparent 75%);
  -webkit-mask-image: radial-gradient(ellipse 70% 60% at 50% 0%, black 30%, transparent 75%);
  pointer-events: none;
}`;
  }
  if (profile.texture === "beams") {
    return `.hero::after {
  content: "";
  position: absolute;
  inset: -40% -10% auto;
  height: 120%;
  background: conic-gradient(from 190deg at 50% 0%, transparent 40%, ${line} 46%, transparent 52%, ${line} 58%, transparent 64%);
  pointer-events: none;
}`;
  }
  return "";
}

export function renderPage(content, profile, options = {}) {
  const primaryCta = content.hero?.ctas?.[0] ?? { label: "Get started", href: "#" };
  const archetype = options.archetype ?? null;
  const patterns = options.patterns ?? [];
  const patternIds = new Set(patterns.map((pattern) => pattern.id));
  const heroVariant = (() => {
    if (patternIds.has("hero-split-product")) return "split";
    if ((content.features?.length ?? 0) >= 3 && !patternIds.has("hero-editorial-lead")) return "split";
    if (patternIds.has("hero-bento-showcase")) return "bento";
    if (patternIds.has("hero-editorial-lead")) return "editorial";
    if (patternIds.has("hero-minimal-statement")) return "minimal";
    return archetype?.heroVariant ?? "centered";
  })();
  const sectionOrder = archetype?.sectionOrder ?? ["hero", "stats", "features", "splits", "social", "extras", "cta"];
  const flags = options.renderFlags ?? tasteRenderFlags(options.taste ?? {});
  const revealClass = flags.showScrollReveal ? "reveal" : "";
  const navVariant = options.navVariant ?? resolveNavVariant(patterns);
  const footerVariant = resolveFooterVariant(patterns);
  const heroOptions = { revealClass, flags };
  const useIconRows = patternIds.has("features-icon-rows");
  const useBentoFeatures = patternIds.has("features-bento-grid");

  const sections = [];
  const catalogSections = renderCatalogSections(content, profile, patterns, {
    sectionOrder: ["logos", "bento", "integrations", "pricing", "faq", "trust", "prose"],
    renderFlags: flags
  });
  const catalogByKey = {
    logos: catalogSections.find((section) => section.includes("logo-cloud")) ?? "",
    bento: catalogSections.find((section) => section.includes("bento-grid")) ?? "",
    integrations: catalogSections.find((section) => section.includes("integrations")) ?? "",
    pricing: catalogSections.find((section) => section.includes('id="pricing"')) ?? "",
    faq: catalogSections.find((section) => section.includes('id="faq"')) ?? "",
    trust: catalogSections.find((section) => section.includes("trust-badge")) ?? "",
    prose: catalogSections.find((section) => section.includes('id="story"')) ?? ""
  };

  if (content.stats?.length) {
    sections.push({ key: "stats", html: `  <section class="stats" aria-label="Highlights">
    <div class="container">
${content.stats.map((stat) => `      <div class="${revealClass}">
        <div class="stat-value">${escapeHtml(stat.value)}</div>
        <div class="stat-label">${escapeHtml(stat.label)}</div>
      </div>`).join("\n")}
    </div>
  </section>` });
  }

  if (content.features?.length && heroVariant !== "bento" && !useBentoFeatures) {
    const brand = escapeHtml(content.brand || "Product");
    if (useIconRows) {
      sections.push({
        key: "features",
        html: renderIconRowFeatures(content, {
          revealClass,
          showSectionKickers: flags.showSectionKickers
        })
      });
    } else {
      const kickerHtml = flags.showSectionKickers
        ? `        <div class="kicker">Why ${brand}</div>\n`
        : "";
      sections.push({ key: "features", html: `  <section class="section" id="features">
    <div class="container">
      <div class="section-head centered ${revealClass}">
${kickerHtml}        <h2>${escapeHtml(content.featuresHeading || "Everything you need, nothing you don't")}</h2>
      </div>
      <div class="card-grid">
${content.features.map((feature) => `        <article class="card ${revealClass}">
          ${flags.showFeatureIcons
    ? `<div class="card-accent" aria-hidden="true"></div>`
    : ""}
          <h3>${escapeHtml(feature.title)}</h3>
          <p>${escapeHtml(feature.body)}</p>
        </article>`).join("\n")}
      </div>
    </div>
  </section>` });
    }
  }

  const splitSections = [];
  const hasPricingSection = Boolean(catalogByKey.pricing) || Boolean(content.pricingTiers?.length);
  const skipSplitHeadings = new Set(["features", "pricing", "sign up today"]);
  if (patternIds.has("features-split-detail")) {
    for (const [index, section] of (content.sections ?? []).entries()) {
      const heading = String(section.heading ?? "").trim();
      const headingKey = heading.toLowerCase();
      if (skipSplitHeadings.has(headingKey)) continue;
      if (/pricing/i.test(heading) && hasPricingSection) continue;
      const items = section.items ?? [];
      const body = String(section.body ?? "").trim();
      if (!body && !items.length) continue;

      const flip = index % 2 === 1;
      splitSections.push(`  <section class="section${index % 2 === 0 ? " alt" : ""}"${headingKey.includes("about") || /why teams/i.test(heading) ? ' id="about"' : ""}>
    <div class="container split">
      ${flip ? "" : `<div class="split-visual ${revealClass}" aria-hidden="true"><div class="split-mesh"></div></div>`}
      <div class="${revealClass}">
        <h3>${escapeHtml(heading)}</h3>
        ${body ? `<p>${escapeHtml(body)}</p>` : ""}
        ${items.length ? `<ul>
${items.map((item) => `          <li>${escapeHtml(item)}</li>`).join("\n")}
        </ul>` : ""}
      </div>
      ${flip ? `<div class="split-visual ${revealClass}" aria-hidden="true"><div class="split-mesh"></div></div>` : ""}
    </div>
  </section>`);
    }
  }
  if (splitSections.length) sections.push({ key: "splits", html: splitSections.join("\n\n") });

  if (content.testimonial) {
    sections.push({ key: "social", html: `  <section class="section quote-band">
    <div class="container ${revealClass}">
      <blockquote>“${escapeHtml(content.testimonial.quote)}”</blockquote>
      ${content.testimonial.author ? `<cite>— ${escapeHtml(content.testimonial.author)}</cite>` : ""}
    </div>
  </section>` });
  }

  for (const [index, testimonial] of (content.testimonials ?? []).slice(1).entries()) {
    sections.push({
      key: `social-${index + 1}`,
      html: `  <section class="section quote-band">
    <div class="container ${revealClass}">
      <blockquote>“${escapeHtml(testimonial.quote)}”</blockquote>
      ${testimonial.author ? `<cite>— ${escapeHtml(testimonial.author)}</cite>` : ""}
    </div>
  </section>`
    });
  }

  const preservedHtml = renderPreservedBlocks(content, revealClass);
  if (preservedHtml) sections.push({ key: "preserved", html: preservedHtml });

  for (const key of ["logos", "bento", "integrations", "pricing", "faq", "trust", "prose", "preserved"]) {
    if (catalogByKey[key]) sections.push({ key, html: catalogByKey[key] });
  }

  const brandName = escapeHtml(content.brand || "Product");
  sections.push({ key: "cta", html: `  <section class="cta-band" id="get-started">
    <div class="container">
      <div class="inner ${revealClass}${flags.showSpotlight ? " spotlight-target" : ""}">
        <h2>${escapeHtml(content.cta?.headline || `Start building with ${content.brand || "us"} today`)}</h2>
        ${content.cta?.subhead ? `<p>${escapeHtml(content.cta.subhead)}</p>` : ""}
        <div class="hero-ctas">
          <a class="btn btn-primary btn-lg" href="${escapeAttr(primaryCta.href)}">${escapeHtml(primaryCta.label)}</a>
        </div>
      </div>
    </div>
  </section>` });

  const orderedHtml = orderSections(sections, sectionOrder);
  const heroHtml = (() => {
    switch (heroVariant) {
      case "split":
        return renderHeroSplit(content, profile, renderHeadline, heroOptions);
      case "bento":
        return renderHeroBento(content, profile, renderHeadline, heroOptions);
      case "editorial":
        return renderHeroEditorial(content, profile, renderHeadline, heroOptions);
      case "minimal":
        return renderHeroMinimal(content, profile, renderHeadline, heroOptions);
      default:
        return buildCenteredHero(content, brandName, primaryCta, content.hero?.ctas?.[1] ?? null, heroOptions);
    }
  })();

  const navHtml = renderSiteNav(content, profile, {
    navVariant,
    showHeroFadeUp: flags.showHeroFadeUp
  });
  const footerHtml = renderSiteFooter(content, profile, { footerVariant });

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(content.title || content.brand || "Home")}</title>
  <meta name="description" content="${escapeAttr(content.description || content.hero?.subhead || "")}">
  <meta name="theme-color" content="${escapeAttr(profile.colors.bg)}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="${profile.fonts.googleImport}" rel="stylesheet">
  <link rel="stylesheet" href="morph-theme.css">
</head>
<body>
${flags.showPageBackdrop ? profileBackdropHtml() : ""}
${navHtml}

  <main>
${heroHtml}

${orderedHtml.join("\n\n")}
  </main>

${footerHtml}

  <script>
    ${pageScripts(flags, profile)}
  </script>
</body>
</html>
`;
}

function buildCenteredHero(content, brand, primaryCta, secondaryCta, options = {}) {
  const { revealClass = "reveal", flags = {} } = options;
  const anim = (index) => (flags.showHeroFadeUp ? ` fade-up fade-up-${index}` : "");
  return `  <section class="hero">
    <div class="container">
      ${flags.showEyebrow && content.hero?.eyebrow ? `<div class="eyebrow ${revealClass}${anim(1)}">${escapeHtml(content.hero.eyebrow)}</div>` : ""}
      <h1 class="${revealClass}${anim(2)}">${renderHeadline(content.hero?.headline || brand || "Welcome")}</h1>
      ${content.hero?.subhead ? `<p class="lede ${revealClass}${anim(3)}">${escapeHtml(content.hero.subhead)}</p>` : ""}
      <div class="hero-ctas ${revealClass}${anim(4)}">
        <a class="btn btn-primary btn-lg" href="${escapeAttr(primaryCta.href)}">${escapeHtml(primaryCta.label)}</a>
        ${secondaryCta ? `<a class="btn btn-ghost btn-lg" href="${escapeAttr(secondaryCta.href)}">${escapeHtml(secondaryCta.label)}</a>` : ""}
      </div>
    </div>
  </section>`;
}

function orderSections(sections, order) {
  const extras = ["logos", "bento", "integrations", "pricing", "faq", "trust", "prose", "preserved"];
  const sequence = [...order];
  for (const key of extras) {
    if (!sequence.includes(key)) sequence.push(key);
  }
  const byKey = Object.fromEntries(sections.map((section) => [section.key, section.html]));
  return sequence.map((key) => byKey[key]).filter(Boolean);
}

// Emphasize the tail of the headline with a solid accent color instead of
// gradient text — gradient clipped text is a common AI slop tell.
function renderHeadline(headline) {
  const words = String(headline).trim().split(/\s+/);
  if (words.length < 3) return `<span class="accent">${escapeHtml(words.join(" "))}</span>`;
  const split = Math.max(1, words.length - Math.min(3, Math.ceil(words.length / 3)));
  const head = escapeHtml(words.slice(0, split).join(" "));
  const tail = escapeHtml(words.slice(split).join(" "));
  return `${head} <span class="accent">${tail}</span>`;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttr(value) {
  return escapeHtml(value).replace(/"/g, "&quot;");
}

function normalizePreservedKey(value) {
  return String(value ?? "").toLowerCase().replace(/\s+/g, " ").trim();
}

function renderPreservedBlocks(content, revealClass) {
  const blocks = content.preservedBlocks ?? [];
  if (!blocks.length) return "";

  const knownText = new Set([
    normalizePreservedKey(content.hero?.headline),
    normalizePreservedKey(content.hero?.subhead),
    ...(content.features ?? []).flatMap((feature) => [
      normalizePreservedKey(feature.title),
      normalizePreservedKey(feature.body)
    ]),
    ...(content.sections ?? []).flatMap((section) => [
      normalizePreservedKey(section.heading),
      normalizePreservedKey(section.body),
      ...(section.items ?? []).map((item) => normalizePreservedKey(item))
    ])
  ].filter(Boolean));

  const parts = blocks.map((block, index) => {
    if (block.type === "paragraph") {
      const key = normalizePreservedKey(block.text);
      if (!key || knownText.has(key)) return "";
      return `      <p class="${revealClass}">${escapeHtml(block.text)}</p>`;
    }
    if (block.type === "table" && block.rows?.length) {
      const rows = block.rows.map((row) =>
        `          <tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join("")}</tr>`
      ).join("\n");
      return `      <div class="table-wrap ${revealClass}">
        <table>
          <tbody>
${rows}
          </tbody>
        </table>
      </div>`;
    }
    if (block.type === "form" && block.fields?.length) {
      const fields = block.fields.map((field) =>
        `          <label>${escapeHtml(field.placeholder || field.name || field.type)}</label>`
      ).join("\n");
      return `      <form class="preserved-form ${revealClass}" aria-label="Original form ${index + 1}">
${fields}
      </form>`;
    }
    return "";
  }).filter(Boolean);

  if (!parts.length) return "";
  return "";
}
