// morph Design Intelligence Database — component pattern library.
//
// Renders a content model extracted from an arbitrary site into a complete,
// production-grade landing page using a design profile. The output is a
// single self-contained HTML document plus a generated design-system
// stylesheet (morph-theme.css).

import { componentStyles, renderCatalogSections, renderHeroSplit } from "./components.js";
import { tasteRenderFlags } from "./taste.js";

export function renderStylesheet(profile, options = {}) {
  const { colors, fonts, radius, shadows } = profile;
  const flags = options.renderFlags ?? tasteRenderFlags(options.taste ?? {});
  const texture = textureLayer(profile);
  const extra = options.includeComponents !== false ? componentStyles(profile) : "";
  const revealMs = flags.revealDurationMs || 0;
  const hoverLift = flags.hoverLift ?? "-2px";
  const sectionScale = flags.sectionPaddingScale ?? 1;
  const sectionPad = sectionScale === 1
    ? "clamp(72px, 9vw, 120px)"
    : `clamp(${Math.round((72 * sectionScale) / 4) * 4}px, 9vw, ${Math.round((120 * sectionScale) / 4) * 4}px)`;

  return `/* ${profile.name} — generated by morph from its design intelligence database.
   Inspired by: ${profile.inspiration} */

:root {
  --bg: ${colors.bg};
  --bg-alt: ${colors.bgAlt};
  --surface: ${colors.surface};
  --surface-raised: ${colors.surfaceRaised};
  --border: ${colors.border};
  --border-strong: ${colors.borderStrong};
  --ink: ${colors.ink};
  --ink-secondary: ${colors.inkSecondary};
  --muted: ${colors.muted};
  --primary: ${colors.primary};
  --primary-hover: ${colors.primaryHover};
  --primary-ink: ${colors.primaryInk};
  --accent: ${colors.accent};
  --focus: ${colors.focus};

  --font-display: ${fonts.displayStack};
  --font-body: ${fonts.bodyStack};
  --font-mono: ${fonts.monoStack};

  --radius-sm: ${radius.sm};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-xl: ${radius.xl};
  --radius-pill: ${radius.pill};

  --shadow-card: ${shadows.card};
  --shadow-raised: ${shadows.raised};
  --shadow-button: ${shadows.button};

  --space-1: 4px;  --space-2: 8px;  --space-3: 12px;  --space-4: 16px;
  --space-5: 24px; --space-6: 32px; --space-7: 48px; --space-8: 64px;
  --space-9: 96px; --space-10: 128px;

  --container: 1120px;

  /* Emil Kowalski motion tokens — ease-out for UI, ease-in-out for movement */
  --ease-out: cubic-bezier(0.23, 1, 0.32, 1);
  --ease-in-out: cubic-bezier(0.77, 0, 0.175, 1);
  --ease-hover: cubic-bezier(0.25, 0.46, 0.45, 0.94);
  --duration-fast: 160ms;
  --duration-ui: 220ms;
}

*, *::before, *::after { box-sizing: border-box; }
* { margin: 0; }

html { scroll-behavior: smooth; }
@media (prefers-reduced-motion: reduce) {
  html { scroll-behavior: auto; }
  *, *::before, *::after { animation: none !important; transition: none !important; }
}

body {
  background: var(--bg);
  color: var(--ink);
  font-family: var(--font-body);
  font-size: 16px;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}

img, svg { display: block; max-width: 100%; }

::selection { background: var(--primary); color: var(--primary-ink); }

a { color: inherit; text-decoration: none; }

:focus-visible {
  outline: 2px solid var(--focus);
  outline-offset: 3px;
  border-radius: var(--radius-sm);
}

.container {
  width: min(var(--container), 100% - 48px);
  margin-inline: auto;
}

/* ── Navigation ─────────────────────────────────────────────────────────── */

.site-nav {
  position: sticky;
  top: 0;
  z-index: 50;
  backdrop-filter: blur(16px) saturate(1.4);
  -webkit-backdrop-filter: blur(16px) saturate(1.4);
  background: color-mix(in srgb, var(--bg) 78%, transparent);
  border-bottom: 1px solid var(--border);
}
.site-nav .container {
  display: flex;
  align-items: center;
  gap: var(--space-6);
  height: 64px;
}
.brand {
  display: flex;
  align-items: center;
  gap: 10px;
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: 17px;
  letter-spacing: ${fonts.displayTracking};
}
.brand-mark {
  width: 26px; height: 26px;
  border-radius: 8px;
  background: var(--primary);
  flex: none;
}
.nav-links {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  margin-left: auto;
  list-style: none;
  padding: 0;
}
.nav-links a {
  padding: 8px 14px;
  border-radius: var(--radius-pill);
  font-size: 14px;
  font-weight: 500;
  color: var(--muted);
  transition: color var(--duration-fast) var(--ease-hover), background var(--duration-fast) var(--ease-hover);
}
.nav-links a:hover { color: var(--ink); background: color-mix(in srgb, var(--ink) 7%, transparent); }
.nav-cta { margin-left: var(--space-3); }

/* ── Buttons ────────────────────────────────────────────────────────────── */

.btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  padding: 12px 24px;
  border-radius: var(--radius-pill);
  border: 1px solid transparent;
  font-family: var(--font-body);
  font-size: 15px;
  font-weight: 600;
  line-height: 1;
  cursor: pointer;
  white-space: nowrap;
  transition: transform var(--duration-fast) var(--ease-out),
              box-shadow var(--duration-fast) var(--ease-out),
              background var(--duration-fast) var(--ease-out),
              border-color var(--duration-fast) var(--ease-out);
}
.btn:active { transform: translateY(1px) scale(0.98); transition-duration: 100ms; }

.btn-primary {
  background: ${colors.buttonGradient};
  color: var(--primary-ink);
  box-shadow: var(--shadow-button);
}
.btn-primary:hover {
  transform: translateY(-1px);
  box-shadow: var(--shadow-button);
}

.btn-ghost {
  background: transparent;
  color: var(--ink);
  border-color: var(--border-strong);
}
.btn-ghost:hover {
  border-color: var(--primary);
  background: color-mix(in srgb, var(--primary) 8%, transparent);
}

.btn-lg { padding: 15px 30px; font-size: 16px; }

/* ── Hero ───────────────────────────────────────────────────────────────── */

.hero {
  position: relative;
  overflow: hidden;
  padding: clamp(88px, 14vw, 160px) 0 clamp(72px, 10vw, 120px);
  text-align: center;
}
${colors.glow !== "none" ? `.hero::before {
  content: "";
  position: absolute;
  inset: 0;
  background: ${colors.glow};
  pointer-events: none;
}` : ""}
${texture}
.hero .container { position: relative; }

.eyebrow {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 7px 16px;
  border-radius: var(--radius-pill);
  border: 1px solid var(--border-strong);
  background: color-mix(in srgb, var(--surface) 65%, transparent);
  font-size: 13px;
  font-weight: 600;
  letter-spacing: 0.02em;
  color: var(--ink-secondary);
  margin-bottom: var(--space-6);
}
.eyebrow::before {
  content: "";
  width: 7px; height: 7px;
  border-radius: 50%;
  background: var(--primary);
  box-shadow: 0 0 10px var(--primary);
}

.hero h1 {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(40px, 7vw, 76px);
  line-height: 1.04;
  letter-spacing: ${fonts.displayTracking};
  max-width: 17ch;
  margin-inline: auto;
  text-wrap: balance;
}
.hero h1 .accent { color: var(--primary); }

.hero .lede {
  margin: var(--space-6) auto 0;
  max-width: 58ch;
  font-size: clamp(17px, 2vw, 20px);
  line-height: 1.65;
  color: var(--muted);
  text-wrap: pretty;
}

.hero-ctas {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  gap: var(--space-4);
  margin-top: var(--space-7);
}

/* ── Stats strip ────────────────────────────────────────────────────────── */

.stats {
  border-block: 1px solid var(--border);
  background: var(--bg-alt);
}
.stats .container {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: var(--space-6);
  padding: var(--space-7) 0;
  text-align: center;
}
.stat-value {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4vw, 40px);
  letter-spacing: ${fonts.displayTracking};
  color: var(--ink);
}
.stat-label {
  margin-top: 6px;
  font-size: 14px;
  color: var(--muted);
}

/* ── Sections ───────────────────────────────────────────────────────────── */

.section { padding: ${sectionPad} 0; }
.section.alt { background: var(--bg-alt); border-block: 1px solid var(--border); }

.section-head {
  max-width: 640px;
  margin-bottom: var(--space-8);
}
.section-head.centered { margin-inline: auto; text-align: center; }
.section-head .kicker {
  font-family: var(--font-mono);
  font-size: 13px;
  font-weight: 500;
  letter-spacing: 0.08em;
  text-transform: uppercase;
  color: var(--primary);
  margin-bottom: var(--space-3);
}
.section-head h2 {
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4.5vw, 44px);
  line-height: 1.12;
  letter-spacing: ${fonts.displayTracking};
  text-wrap: balance;
}
.section-head p {
  margin-top: var(--space-4);
  font-size: 17px;
  color: var(--muted);
  text-wrap: pretty;
}

/* ── Feature cards ──────────────────────────────────────────────────────── */

.card-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: var(--space-5);
}
.card {
  position: relative;
  padding: var(--space-6);
  border-radius: var(--radius-lg);
  border: 1px solid var(--border);
  background: var(--surface);
  box-shadow: var(--shadow-card);
  transition: transform var(--duration-ui) var(--ease-out),
              border-color var(--duration-ui) var(--ease-out),
              box-shadow var(--duration-ui) var(--ease-out);
}
.card:hover {
  transform: translateY(${hoverLift});
  border-color: ${colors.cardHoverBorder};
  box-shadow: var(--shadow-raised);
}
.card-accent {
  width: 3px;
  height: 28px;
  border-radius: 999px;
  background: var(--primary);
  margin-bottom: var(--space-4);
}
.card h3 {
  font-family: var(--font-display);
  font-size: 19px;
  font-weight: 600;
  letter-spacing: -0.01em;
  margin-bottom: var(--space-3);
}
.card p { font-size: 15px; line-height: 1.65; color: var(--muted); }

/* ── Prose / detail sections ────────────────────────────────────────────── */

.split {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(320px, 1fr));
  gap: var(--space-8);
  align-items: center;
}
.split .panel {
  border-radius: var(--radius-xl);
  border: 1px solid var(--border);
  background: var(--surface);
  box-shadow: var(--shadow-card);
  padding: var(--space-7);
  min-height: 240px;
  display: grid;
  place-items: center;
}
.split .panel .glyph {
  font-family: var(--font-display);
  font-size: 64px;
  font-weight: ${fonts.displayWeight};
  color: var(--primary);
}
.split h3 {
  font-family: var(--font-display);
  font-size: clamp(24px, 3vw, 32px);
  font-weight: ${fonts.displayWeight};
  letter-spacing: ${fonts.displayTracking};
  line-height: 1.15;
  margin-bottom: var(--space-4);
  text-wrap: balance;
}
.split p { color: var(--muted); font-size: 16.5px; text-wrap: pretty; }
.split ul {
  margin-top: var(--space-5);
  padding: 0;
  list-style: none;
  display: grid;
  gap: var(--space-3);
}
.split li {
  display: flex;
  gap: 12px;
  align-items: baseline;
  font-size: 15.5px;
  color: var(--ink-secondary);
}
.split li::before {
  content: "→";
  color: var(--primary);
  font-weight: 700;
  flex: none;
}

/* ── Quote band ─────────────────────────────────────────────────────────── */

.quote-band { text-align: center; }
.quote-band blockquote {
  font-family: var(--font-display);
  font-size: clamp(22px, 3.4vw, 34px);
  font-weight: 500;
  line-height: 1.35;
  letter-spacing: -0.01em;
  max-width: 26ch;
  margin-inline: auto;
  text-wrap: balance;
}
.quote-band cite {
  display: block;
  margin-top: var(--space-5);
  font-style: normal;
  font-size: 15px;
  color: var(--muted);
}

/* ── CTA band ───────────────────────────────────────────────────────────── */

.cta-band { padding: clamp(72px, 9vw, 110px) 0; }
.cta-band .inner {
  position: relative;
  overflow: hidden;
  border-radius: var(--radius-xl);
  border: 1px solid var(--border-strong);
  background: var(--surface);
  box-shadow: var(--shadow-raised);
  padding: clamp(48px, 7vw, 88px) var(--space-6);
  text-align: center;
}
.cta-band .inner::before {
  content: "";
  position: absolute;
  inset: 0;
  background: ${colors.glow === "none"
    ? `linear-gradient(180deg, color-mix(in srgb, var(--primary) 6%, transparent), transparent)`
    : colors.glow};
  pointer-events: none;
}
.cta-band h2 {
  position: relative;
  font-family: var(--font-display);
  font-weight: ${fonts.displayWeight};
  font-size: clamp(28px, 4.5vw, 44px);
  letter-spacing: ${fonts.displayTracking};
  line-height: 1.1;
  max-width: 20ch;
  margin-inline: auto;
  text-wrap: balance;
}
.cta-band p {
  position: relative;
  margin: var(--space-4) auto 0;
  max-width: 52ch;
  color: var(--muted);
  font-size: 17px;
}
.cta-band .hero-ctas { position: relative; }

/* ── Footer ─────────────────────────────────────────────────────────────── */

.site-footer {
  border-top: 1px solid var(--border);
  background: var(--bg-alt);
  padding: var(--space-8) 0 var(--space-7);
}
.site-footer .top {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-6);
  align-items: center;
  justify-content: space-between;
  margin-bottom: var(--space-6);
}
.footer-links {
  display: flex;
  flex-wrap: wrap;
  gap: var(--space-2);
  list-style: none;
  padding: 0;
}
.footer-links a {
  padding: 6px 12px;
  border-radius: var(--radius-pill);
  font-size: 14px;
  color: var(--muted);
  transition: color var(--duration-fast) var(--ease-hover);
}
.footer-links a:hover { color: var(--ink); }
.site-footer .legal {
  font-size: 13.5px;
  color: var(--muted);
  border-top: 1px solid var(--border);
  padding-top: var(--space-5);
}

/* ── Reveal-on-scroll ───────────────────────────────────────────────────── */

.reveal {
  opacity: ${revealMs > 0 ? "0" : "1"};
  transform: ${revealMs > 0 ? "translateY(14px)" : "none"};
  transition: opacity ${revealMs}ms var(--ease-out), transform ${revealMs}ms var(--ease-out);
}
.reveal.in { opacity: 1; transform: none; }
@media (prefers-reduced-motion: reduce) {
  .reveal { opacity: 1; transform: none; }
}

/* ── Responsive ─────────────────────────────────────────────────────────── */

@media (max-width: 720px) {
  .nav-links { display: none; }
  .nav-cta { display: inline-flex; margin-left: auto; }
  .hero-ctas .btn { width: 100%; max-width: 340px; }
  .site-nav .container { gap: var(--space-4); }
}
${extra}
`;
}

function textureLayer(profile) {
  const line = profile.mode === "dark" ? "rgba(255,255,255,0.04)" : "rgba(15,23,42,0.04)";
  if (profile.texture === "grid" || profile.texture === "dots") {
    return `.hero::after {
  content: "";
  position: absolute;
  inset: 0;
  background-image: radial-gradient(${line} 1px, transparent 1px);
  background-size: 28px 28px;
  mask-image: radial-gradient(ellipse 70% 60% at 50% 0%, black 30%, transparent 75%);
  -webkit-mask-image: radial-gradient(ellipse 70% 60% at 50% 0%, black 30%, transparent 75%);
  pointer-events: none;
}`;
  }
  if (profile.texture === "beams") {
    return `.hero::after {
  content: "";
  position: absolute;
  inset: -40% -10% auto;
  height: 120%;
  background: conic-gradient(from 190deg at 50% 0%, transparent 40%, ${line} 46%, transparent 52%, ${line} 58%, transparent 64%);
  pointer-events: none;
}`;
  }
  return "";
}

export function renderPage(content, profile, options = {}) {
  const brand = escapeHtml(content.brand || "Product");
  const navLinks = (content.nav ?? []).slice(0, 5);
  const primaryCta = content.hero?.ctas?.[0] ?? { label: "Get started", href: "#" };
  const secondaryCta = content.hero?.ctas?.[1] ?? null;
  const archetype = options.archetype ?? null;
  const heroVariant = archetype?.heroVariant ?? "centered";
  const patterns = options.patterns ?? [];
  const sectionOrder = archetype?.sectionOrder ?? ["hero", "stats", "features", "splits", "social", "extras", "cta"];
  const flags = options.renderFlags ?? tasteRenderFlags(options.taste ?? {});
  const revealClass = flags.showScrollReveal ? "reveal" : "";

  const sections = [];
  const catalogSections = renderCatalogSections(content, profile, patterns, {
    sectionOrder: ["logos", "bento", "integrations", "pricing", "faq", "trust"],
    renderFlags: flags
  });
  const catalogByKey = {
    logos: catalogSections.find((section) => section.includes("logo-cloud")) ?? "",
    bento: catalogSections.find((section) => section.includes("bento-grid")) ?? "",
    integrations: catalogSections.find((section) => section.includes("integrations")) ?? "",
    pricing: catalogSections.find((section) => section.includes('id="pricing"')) ?? "",
    faq: catalogSections.find((section) => section.includes('id="faq"')) ?? "",
    trust: catalogSections.find((section) => section.includes("trust-badge")) ?? ""
  };

  if (content.stats?.length) {
    sections.push({ key: "stats", html: `  <section class="stats" aria-label="Highlights">
    <div class="container">
${content.stats.slice(0, 4).map((stat) => `      <div class="${revealClass}">
        <div class="stat-value">${escapeHtml(stat.value)}</div>
        <div class="stat-label">${escapeHtml(stat.label)}</div>
      </div>`).join("\n")}
    </div>
  </section>` });
  }

  if (content.features?.length && heroVariant !== "bento") {
    const kickerHtml = flags.showSectionKickers
      ? `        <div class="kicker">Why ${brand}</div>\n`
      : "";
    sections.push({ key: "features", html: `  <section class="section" id="features">
    <div class="container">
      <div class="section-head centered ${revealClass}">
${kickerHtml}        <h2>${escapeHtml(content.featuresHeading || "Everything you need, nothing you don't")}</h2>
      </div>
      <div class="card-grid">
${content.features.slice(0, 9).map((feature, index) => `        <article class="card ${revealClass}">
          ${flags.showFeatureIcons
    ? `<div class="card-accent" aria-hidden="true"></div>`
    : ""}
          <h3>${escapeHtml(feature.title)}</h3>
          <p>${escapeHtml(feature.body)}</p>
        </article>`).join("\n")}
      </div>
    </div>
  </section>` });
  }

  const splitSections = [];
  for (const [index, section] of (content.sections ?? []).slice(0, 4).entries()) {
    const flip = index % 2 === 1;
    const items = (section.items ?? []).slice(0, 5);
    splitSections.push(`  <section class="section${index % 2 === 0 ? " alt" : ""}">
    <div class="container split">
      ${flip ? "" : `<div class="panel ${revealClass}" aria-hidden="true"><span class="glyph">${escapeHtml(String(index + 1).padStart(2, "0"))}</span></div>`}
      <div class="${revealClass}">
        <h3>${escapeHtml(section.heading)}</h3>
        ${section.body ? `<p>${escapeHtml(section.body)}</p>` : ""}
        ${items.length ? `<ul>
${items.map((item) => `          <li>${escapeHtml(item)}</li>`).join("\n")}
        </ul>` : ""}
      </div>
      ${flip ? `<div class="panel ${revealClass}" aria-hidden="true"><span class="glyph">${escapeHtml(String(index + 1).padStart(2, "0"))}</span></div>` : ""}
    </div>
  </section>`);
  }
  if (splitSections.length) sections.push({ key: "splits", html: splitSections.join("\n\n") });

  if (content.testimonial) {
    sections.push({ key: "social", html: `  <section class="section quote-band">
    <div class="container ${revealClass}">
      <blockquote>“${escapeHtml(content.testimonial.quote)}”</blockquote>
      ${content.testimonial.author ? `<cite>— ${escapeHtml(content.testimonial.author)}</cite>` : ""}
    </div>
  </section>` });
  }

  for (const key of ["logos", "bento", "integrations", "pricing", "faq", "trust"]) {
    if (catalogByKey[key]) sections.push({ key, html: catalogByKey[key] });
  }

  sections.push({ key: "cta", html: `  <section class="cta-band" id="get-started">
    <div class="container">
      <div class="inner ${revealClass}">
        <h2>${escapeHtml(content.cta?.headline || `Start building with ${content.brand || "us"} today`)}</h2>
        ${content.cta?.subhead ? `<p>${escapeHtml(content.cta.subhead)}</p>` : ""}
        <div class="hero-ctas">
          <a class="btn btn-primary btn-lg" href="${escapeAttr(primaryCta.href)}">${escapeHtml(primaryCta.label)}</a>
        </div>
      </div>
    </div>
  </section>` });

  const orderedHtml = orderSections(sections, sectionOrder);
  const heroHtml = heroVariant === "split"
    ? renderHeroSplit(content, profile, renderHeadline, { revealClass, flags })
    : buildCenteredHero(content, brand, primaryCta, secondaryCta, { revealClass, flags });

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(content.title || content.brand || "Home")}</title>
  <meta name="description" content="${escapeAttr(content.description || content.hero?.subhead || "")}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="${profile.fonts.googleImport}" rel="stylesheet">
  <link rel="stylesheet" href="morph-theme.css">
</head>
<body>
  <header class="site-nav">
    <div class="container">
      <a class="brand" href="#"><span class="brand-mark" aria-hidden="true"></span>${brand}</a>
      ${navLinks.length ? `<nav aria-label="Primary">
        <ul class="nav-links">
${navLinks.map((link) => `          <li><a href="${escapeAttr(link.href)}">${escapeHtml(link.label)}</a></li>`).join("\n")}
        </ul>
      </nav>` : ""}
      <a class="btn btn-primary nav-cta" href="${escapeAttr(primaryCta.href)}">${escapeHtml(primaryCta.label)}</a>
    </div>
  </header>

  <main>
${heroHtml}

${orderedHtml.join("\n\n")}
  </main>

  <footer class="site-footer">
    <div class="container">
      <div class="top">
        <a class="brand" href="#"><span class="brand-mark" aria-hidden="true"></span>${brand}</a>
        ${navLinks.length ? `<ul class="footer-links">
${navLinks.map((link) => `          <li><a href="${escapeAttr(link.href)}">${escapeHtml(link.label)}</a></li>`).join("\n")}
        </ul>` : ""}
      </div>
      <p class="legal">© ${new Date().getFullYear()} ${brand}. ${escapeHtml(content.footerText || "All rights reserved.")}</p>
    </div>
  </footer>

  <script>
    (function () {
      var revealEnabled = ${flags.showScrollReveal ? "true" : "false"};
      if (!revealEnabled || window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
        document.querySelectorAll(".reveal").forEach(function (el) { el.classList.add("in"); });
        return;
      }
      var observer = new IntersectionObserver(function (entries) {
        entries.forEach(function (entry) {
          if (entry.isIntersecting) {
            entry.target.classList.add("in");
            observer.unobserve(entry.target);
          }
        });
      }, { threshold: 0.12 });
      document.querySelectorAll(".reveal").forEach(function (el) { observer.observe(el); });
    })();
  </script>
</body>
</html>
`;
}

function buildCenteredHero(content, brand, primaryCta, secondaryCta, options = {}) {
  const { revealClass = "reveal", flags = {} } = options;
  return `  <section class="hero">
    <div class="container">
      ${flags.showEyebrow && content.hero?.eyebrow ? `<div class="eyebrow ${revealClass}">${escapeHtml(content.hero.eyebrow)}</div>` : ""}
      <h1 class="${revealClass}">${renderHeadline(content.hero?.headline || brand || "Welcome")}</h1>
      ${content.hero?.subhead ? `<p class="lede ${revealClass}">${escapeHtml(content.hero.subhead)}</p>` : ""}
      <div class="hero-ctas ${revealClass}">
        <a class="btn btn-primary btn-lg" href="${escapeAttr(primaryCta.href)}">${escapeHtml(primaryCta.label)}</a>
        ${secondaryCta ? `<a class="btn btn-ghost btn-lg" href="${escapeAttr(secondaryCta.href)}">${escapeHtml(secondaryCta.label)}</a>` : ""}
      </div>
    </div>
  </section>`;
}

function orderSections(sections, order) {
  const extras = ["logos", "bento", "integrations", "pricing", "faq", "trust"];
  const sequence = [...order];
  for (const key of extras) {
    if (!sequence.includes(key)) sequence.push(key);
  }
  const byKey = Object.fromEntries(sections.map((section) => [section.key, section.html]));
  return sequence.map((key) => byKey[key]).filter(Boolean);
}

// Emphasize the tail of the headline with a solid accent color instead of
// gradient text — gradient clipped text is a common AI slop tell.
function renderHeadline(headline) {
  const words = String(headline).trim().split(/\s+/);
  if (words.length < 3) return `<span class="accent">${escapeHtml(words.join(" "))}</span>`;
  const split = Math.max(1, words.length - Math.min(3, Math.ceil(words.length / 3)));
  const head = escapeHtml(words.slice(0, split).join(" "));
  const tail = escapeHtml(words.slice(split).join(" "));
  return `${head} <span class="accent">${tail}</span>`;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttr(value) {
  return escapeHtml(value).replace(/"/g, "&quot;");
}
