// morph Design Intelligence Database — reference corpus.
//
// A massive, searchable library of production web UI grammars distilled from
// frontier and Fortune-class product sites. Used by the retrieval engine to
// match incoming agent-generated sites to the visual language of billion-dollar
// companies — without copying layouts or assets directly.

export const CORPUS_TIERS = ["startup", "growth", "enterprise", "fortune500", "iconic"];

export const INDUSTRY_VOCABULARY = {
  "developer-tools": [
    "developer", "dev", "api", "sdk", "cli", "infra", "deploy", "code", "engineering",
    "terminal", "git", "open source", "database", "serverless", "backend", "frontend"
  ],
  fintech: [
    "payment", "payments", "finance", "fintech", "bank", "banking", "money", "billing",
    "invoice", "checkout", "wallet", "card", "lending", "invest", "trading", "crypto"
  ],
  saas: [
    "saas", "software", "platform", "workflow", "automation", "productivity", "team",
    "collaboration", "project", "task", "manage", "crm", "subscription", "cloud"
  ],
  "creative-tools": [
    "design", "creative", "portfolio", "motion", "animation", "figma", "canvas",
    "editor", "visual", "brand", "agency", "studio", "no-code"
  ],
  commerce: [
    "commerce", "ecommerce", "shop", "store", "retail", "merchant", "marketplace",
    "cart", "checkout", "inventory", "sell", "buy"
  ],
  enterprise: [
    "enterprise", "b2b", "compliance", "security", "audit", "sso", "governance",
    "scale", "global", "fortune", "procurement", "vendor"
  ],
  media: [
    "media", "streaming", "video", "music", "podcast", "content", "entertainment",
    "news", "publish", "editorial", "story", "journalism"
  ],
  health: [
    "health", "wellness", "medical", "fitness", "therapy", "mental", "care",
    "patient", "clinical", "nutrition", "meditation"
  ],
  ai: [
    "ai", "artificial intelligence", "machine learning", "ml", "model", "llm",
    "agent", "copilot", "inference", "training", "neural"
  ],
  gaming: [
    "gaming", "game", "play", "esports", "3d", "metaverse", "player", "studio"
  ],
  travel: [
    "travel", "hotel", "flight", "booking", "trip", "vacation", "destination", "host"
  ],
  education: [
    "education", "learn", "course", "student", "school", "university", "training", "tutorial"
  ],
  legal: [
    "legal", "law", "compliance", "contract", "attorney", "litigation", "regulatory"
  ],
  marketing: [
    "marketing", "campaign", "ads", "analytics", "growth", "conversion", "seo", "email"
  ],
  hardware: [
    "hardware", "device", "chip", "sensor", "iot", "robotics", "manufacturing", "electronics"
  ],
  social: [
    "social", "community", "network", "chat", "forum", "messaging", "creator", "follow"
  ],
  nonprofit: [
    "nonprofit", "charity", "donate", "impact", "mission", "volunteer", "sustainability"
  ]
};

/** @typedef {import("./reference-corpus.js").UiReference} UiReference */

function ref(id, name, tier, industry, profileHint, archetypeHint, tags, keywords, patterns = []) {
  return { id, name, tier, industry, profileHint, archetypeHint, tags, keywords, patterns };
}

// ── Developer tools & infra ─────────────────────────────────────────────────
const DEVELOPER_REFS = [
  ref("linear", "Linear", "iconic", "developer-tools", "aurora-dark", "developer-product",
    ["developer", "dark", "minimal", "gradient", "issue", "roadmap"],
    ["issue tracking", "project management", "software development", "sprint", "roadmap", "bugs"]),
  ref("vercel", "Vercel", "iconic", "developer-tools", "aurora-dark", "developer-product",
    ["developer", "deploy", "dark", "edge", "nextjs"],
    ["deployment", "hosting", "frontend cloud", "serverless", "preview"]),
  ref("supabase", "Supabase", "growth", "developer-tools", "signal-green", "developer-product",
    ["database", "open-source", "green", "postgres", "backend"],
    ["postgres", "database", "auth", "storage", "realtime", "backend as a service"]),
  ref("stripe-dev", "Stripe Developers", "iconic", "developer-tools", "meridian-light", "developer-product",
    ["api", "payments", "docs", "developer"],
    ["payment api", "webhooks", "documentation", "integration", "sdk"]),
  ref("github", "GitHub", "fortune500", "developer-tools", "aurora-dark", "developer-product",
    ["developer", "git", "open-source", "collaboration"],
    ["repository", "pull request", "actions", "copilot", "version control"]),
  ref("gitlab", "GitLab", "enterprise", "developer-tools", "cobalt-enterprise", "developer-product",
    ["devops", "ci", "enterprise", "developer"],
    ["devops", "pipeline", "merge request", "self-hosted"]),
  ref("docker", "Docker", "enterprise", "developer-tools", "aurora-dark", "developer-product",
    ["container", "developer", "infra"],
    ["container", "kubernetes", "image", "compose", "microservices"]),
  ref("terraform", "HashiCorp Terraform", "enterprise", "developer-tools", "cobalt-enterprise", "enterprise-trust",
    ["infra", "cloud", "enterprise", "iac"],
    ["infrastructure as code", "terraform", "provision", "multi-cloud"]),
  ref("cloudflare", "Cloudflare", "enterprise", "developer-tools", "aurora-dark", "developer-product",
    ["cdn", "security", "edge", "developer"],
    ["cdn", "dns", "workers", "ddos", "edge network"]),
  ref("datadog", "Datadog", "enterprise", "developer-tools", "cobalt-enterprise", "enterprise-trust",
    ["observability", "monitoring", "enterprise"],
    ["monitoring", "apm", "logs", "metrics", "observability"]),
  ref("sentry", "Sentry", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["errors", "monitoring", "developer"],
    ["error tracking", "performance", "crash reporting", "debugging"]),
  ref("postman", "Postman", "growth", "developer-tools", "coral-marketing", "developer-product",
    ["api", "testing", "developer"],
    ["api testing", "collections", "mock server", "documentation"]),
  ref("clerk", "Clerk", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["auth", "developer", "purple"],
    ["authentication", "user management", "sign in", "session"]),
  ref("planetscale", "PlanetScale", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["database", "mysql", "developer"],
    ["mysql", "branching", "serverless database", "vitess"]),
  ref("raycast", "Raycast", "growth", "developer-tools", "aurora-dark", "minimal-showcase",
    ["productivity", "mac", "developer"],
    ["launcher", "shortcuts", "productivity", "extensions"]),
  ref("resend", "Resend", "startup", "developer-tools", "aurora-dark", "developer-product",
    ["email", "api", "developer"],
    ["transactional email", "deliverability", "react email"]),
  ref("tailwind", "Tailwind CSS", "iconic", "developer-tools", "signal-green", "developer-product",
    ["css", "developer", "utility"],
    ["utility css", "design system", "components", "styling"]),
  ref("prisma", "Prisma", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["orm", "database", "typescript"],
    ["orm", "schema", "migration", "type-safe database"]),
  ref("fly-io", "Fly.io", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["deploy", "edge", "developer"],
    ["global deployment", "machines", "postgres", "edge apps"]),
  ref("railway", "Railway", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["deploy", "infra", "developer"],
    ["infrastructure", "deploy", "database", "templates"]),
  ref("render", "Render", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["hosting", "deploy", "developer"],
    ["cloud hosting", "static sites", "background workers"]),
  ref("neon", "Neon", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["postgres", "serverless", "database"],
    ["serverless postgres", "branching", "scale to zero"]),
  ref("turso", "Turso", "startup", "developer-tools", "aurora-dark", "developer-product",
    ["sqlite", "edge", "database"],
    ["edge database", "libsql", "replication"]),
  ref("deno", "Deno", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["runtime", "typescript", "javascript"],
    ["javascript runtime", "deploy", "typescript first"]),
  ref("bun", "Bun", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["runtime", "javascript", "fast"],
    ["javascript runtime", "bundler", "package manager"]),
  ref("cursor", "Cursor", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["ai", "editor", "code"],
    ["ai code editor", "copilot", "agent", "ide"]),
  ref("replit", "Replit", "growth", "developer-tools", "halcyon-blue", "developer-product",
    ["ide", "collaboration", "deploy"],
    ["online ide", "collaborative coding", "deploy"]),
  ref("stackblitz", "StackBlitz", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["webcontainer", "ide", "developer"],
    ["in-browser ide", "webcontainer", "instant dev"]),
  ref("codesandbox", "CodeSandbox", "growth", "developer-tools", "citrus-creative", "landing-bento",
    ["sandbox", "react", "collaboration"],
    ["online sandbox", "micro frontends", "collaboration"]),
  ref("netlify", "Netlify", "growth", "developer-tools", "signal-green", "developer-product",
    ["jamstack", "deploy", "developer"],
    ["static hosting", "serverless functions", "jamstack"])
];

// ── Fintech & payments ──────────────────────────────────────────────────────
const FINTECH_REFS = [
  ref("stripe", "Stripe", "iconic", "fintech", "meridian-light", "landing-split",
    ["payments", "light", "beams", "enterprise"],
    ["payments", "checkout", "billing", "connect", "terminal"]),
  ref("ramp", "Ramp", "growth", "fintech", "midnight-fintech", "saas-pricing",
    ["finance", "dark", "enterprise", "corporate card"],
    ["corporate card", "expense", "spend management", "finance automation"]),
  ref("mercury", "Mercury", "growth", "fintech", "midnight-fintech", "landing-split",
    ["banking", "startup", "dark"],
    ["startup banking", "treasury", "accounts", "wire"]),
  ref("plaid", "Plaid", "enterprise", "fintech", "meridian-light", "enterprise-trust",
    ["open banking", "api", "fintech"],
    ["bank linking", "financial data", "payments infrastructure"]),
  ref("brex", "Brex", "enterprise", "fintech", "midnight-fintech", "enterprise-trust",
    ["corporate card", "enterprise", "finance"],
    ["corporate card", "expense management", "startup finance"]),
  ref("square", "Square", "fortune500", "fintech", "meridian-light", "landing-split",
    ["pos", "payments", "commerce"],
    ["point of sale", "payments", "invoices", "hardware"]),
  ref("paypal", "PayPal", "fortune500", "fintech", "meridian-light", "landing-classic",
    ["payments", "wallet", "consumer"],
    ["digital wallet", "send money", "checkout", "business"]),
  ref("coinbase", "Coinbase", "fortune500", "fintech", "aurora-dark", "landing-classic",
    ["crypto", "exchange", "web3"],
    ["cryptocurrency", "bitcoin", "ethereum", "wallet", "trading"]),
  ref("robinhood", "Robinhood", "fortune500", "fintech", "signal-green", "landing-classic",
    ["investing", "trading", "consumer"],
    ["stock trading", "invest", "crypto", "retirement"]),
  ref("wise", "Wise", "enterprise", "fintech", "meridian-light", "landing-split",
    ["transfer", "international", "money"],
    ["international transfer", "multi-currency", "borderless"]),
  ref("affirm", "Affirm", "enterprise", "fintech", "meridian-light", "saas-pricing",
    ["bnpl", "payments", "consumer"],
    ["buy now pay later", "installments", "checkout"]),
  ref("klarna", "Klarna", "enterprise", "fintech", "obsidian-lux", "landing-bento",
    ["bnpl", "payments", "consumer"],
    ["buy now pay later", "shopping", "payments"]),
  ref("chime", "Chime", "enterprise", "fintech", "signal-green", "landing-classic",
    ["neobank", "banking", "consumer"],
    ["mobile banking", "no fees", "direct deposit"]),
  ref("gusto", "Gusto", "enterprise", "fintech", "halcyon-blue", "saas-pricing",
    ["payroll", "hr", "small business"],
    ["payroll", "benefits", "hr platform", "small business"]),
  ref("deel", "Deel", "enterprise", "fintech", "cobalt-enterprise", "enterprise-trust",
    ["payroll", "global", "compliance"],
    ["global payroll", "contractor", "compliance", "eor"])
];

// ── SaaS & productivity ─────────────────────────────────────────────────────
const SAAS_REFS = [
  ref("notion", "Notion", "iconic", "saas", "atelier-warm", "landing-classic",
    ["warm", "consumer", "workspace", "docs"],
    ["notes", "wiki", "workspace", "collaboration", "docs", "database"]),
  ref("intercom", "Intercom", "enterprise", "saas", "halcyon-blue", "landing-split",
    ["support", "chat", "friendly", "messaging"],
    ["customer messaging", "support", "chatbot", "help desk"]),
  ref("cal-com", "Cal.com", "growth", "saas", "halcyon-blue", "saas-pricing",
    ["scheduling", "open-source", "calendar"],
    ["scheduling", "calendar", "booking", "meetings"]),
  ref("loom", "Loom", "growth", "saas", "citrus-creative", "landing-split",
    ["video", "async", "friendly"],
    ["async video", "screen recording", "communication"]),
  ref("slack", "Slack", "fortune500", "saas", "halcyon-blue", "landing-classic",
    ["messaging", "team", "workspace"],
    ["team chat", "channels", "integrations", "workflow"]),
  ref("asana", "Asana", "enterprise", "saas", "halcyon-blue", "landing-classic",
    ["project", "task", "team"],
    ["project management", "tasks", "timeline", "goals"]),
  ref("monday", "Monday.com", "enterprise", "saas", "coral-marketing", "landing-bento",
    ["work os", "colorful", "project"],
    ["work management", "boards", "automations", "crm"]),
  ref("clickup", "ClickUp", "enterprise", "saas", "halcyon-blue", "saas-pricing",
    ["productivity", "project", "all-in-one"],
    ["project management", "docs", "goals", "tasks", "time tracking"]),
  ref("airtable", "Airtable", "enterprise", "saas", "citrus-creative", "landing-bento",
    ["database", "spreadsheet", "no-code"],
    ["spreadsheet database", "workflow", "apps", "automation"]),
  ref("zapier", "Zapier", "enterprise", "saas", "coral-marketing", "landing-classic",
    ["automation", "integration", "workflow"],
    ["automation", "integrations", "zaps", "workflow"]),
  ref("miro", "Miro", "enterprise", "saas", "citrus-creative", "landing-bento",
    ["whiteboard", "collaboration", "visual"],
    ["online whiteboard", "brainstorm", "workshop", "diagram"]),
  ref("figjam", "FigJam", "growth", "saas", "citrus-creative", "landing-bento",
    ["whiteboard", "figma", "collaboration"],
    ["online whiteboard", "workshop", "sticky notes"]),
  ref("canva", "Canva", "fortune500", "saas", "citrus-creative", "landing-bento",
    ["design", "templates", "consumer"],
    ["graphic design", "templates", "presentations", "social media"]),
  ref("dropbox", "Dropbox", "fortune500", "saas", "halcyon-blue", "landing-classic",
    ["files", "storage", "sync"],
    ["cloud storage", "file sharing", "sync", "backup"]),
  ref("box", "Box", "enterprise", "saas", "cobalt-enterprise", "enterprise-trust",
    ["enterprise", "content", "security"],
    ["content management", "enterprise file sharing", "compliance"]),
  ref("docusign", "DocuSign", "fortune500", "saas", "meridian-light", "enterprise-trust",
    ["esign", "contracts", "enterprise"],
    ["electronic signature", "agreements", "workflow"]),
  ref("hubspot", "HubSpot", "fortune500", "marketing", "coral-marketing", "saas-pricing",
    ["crm", "marketing", "orange"],
    ["crm", "inbound marketing", "sales hub", "automation"]),
  ref("salesforce", "Salesforce", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["crm", "enterprise", "cloud"],
    ["crm", "sales cloud", "service cloud", "enterprise platform"]),
  ref("zendesk", "Zendesk", "enterprise", "saas", "halcyon-blue", "landing-split",
    ["support", "helpdesk", "customer"],
    ["customer support", "ticketing", "help center", "chat"]),
  ref("freshworks", "Freshworks", "enterprise", "saas", "halcyon-blue", "saas-pricing",
    ["crm", "support", "saas"],
    ["customer engagement", "crm", "it service management"]),
  ref("atlassian", "Atlassian", "fortune500", "saas", "signal-green", "enterprise-trust",
    ["jira", "confluence", "developer"],
    ["jira", "confluence", "project tracking", "documentation"]),
  ref("todoist", "Todoist", "growth", "saas", "halcyon-blue", "landing-classic",
    ["task", "productivity", "personal"],
    ["todo list", "tasks", "productivity", "projects"]),
  ref("basecamp", "Basecamp", "growth", "saas", "atelier-warm", "landing-classic",
    ["project", "simple", "team"],
    ["project management", "message board", "schedules", "docs"]),
  ref("coda", "Coda", "growth", "saas", "atelier-warm", "landing-bento",
    ["docs", "automation", "workspace"],
    ["doc platform", "tables", "automations", "apps"]),
  ref("retool", "Retool", "enterprise", "saas", "aurora-dark", "developer-product",
    ["internal tools", "low-code", "developer"],
    ["internal tools", "admin panels", "workflows", "database ui"])
];

// ── AI & research ───────────────────────────────────────────────────────────
const AI_REFS = [
  ref("openai", "OpenAI", "iconic", "ai", "monolith-mono", "minimal-showcase",
    ["ai", "research", "minimal", "frontier"],
    ["artificial intelligence", "gpt", "chatgpt", "research", "models"]),
  ref("anthropic", "Anthropic", "iconic", "ai", "monolith-mono", "minimal-showcase",
    ["ai", "safety", "research", "claude"],
    ["ai safety", "claude", "constitutional ai", "research"]),
  ref("midjourney", "Midjourney", "iconic", "ai", "obsidian-lux", "landing-bento",
    ["generative", "creative", "imagery"],
    ["image generation", "ai art", "creative tools"]),
  ref("runway", "Runway", "growth", "ai", "obsidian-lux", "landing-bento",
    ["video", "generative", "creative"],
    ["ai video", "generative media", "creative suite"]),
  ref("huggingface", "Hugging Face", "iconic", "ai", "signal-green", "developer-product",
    ["ml", "open-source", "models"],
    ["machine learning", "models", "transformers", "hub"]),
  ref("cohere", "Cohere", "enterprise", "ai", "cobalt-enterprise", "enterprise-trust",
    ["nlp", "enterprise", "api"],
    ["language models", "enterprise ai", "retrieval", "embeddings"]),
  ref("mistral", "Mistral AI", "growth", "ai", "aurora-dark", "developer-product",
    ["open models", "frontier", "european"],
    ["open weight models", "llm", "inference"]),
  ref("perplexity", "Perplexity", "growth", "ai", "monolith-mono", "minimal-showcase",
    ["search", "answer engine", "research"],
    ["ai search", "answers", "research assistant"]),
  ref("character-ai", "Character.AI", "growth", "ai", "obsidian-lux", "landing-bento",
    ["chat", "characters", "consumer"],
    ["ai characters", "roleplay", "conversation"]),
  ref("jasper", "Jasper", "enterprise", "ai", "coral-marketing", "saas-pricing",
    ["marketing", "copywriting", "brand"],
    ["ai copywriting", "marketing content", "brand voice"]),
  ref("copy-ai", "Copy.ai", "growth", "ai", "coral-marketing", "landing-classic",
    ["copywriting", "marketing", "workflow"],
    ["ai writing", "sales copy", "content generation"]),
  ref("notion-ai", "Notion AI", "growth", "ai", "atelier-warm", "landing-classic",
    ["workspace", "writing", "productivity"],
    ["ai writing", "summarize", "workspace assistant"]),
  ref("github-copilot", "GitHub Copilot", "enterprise", "ai", "aurora-dark", "developer-product",
    ["code", "copilot", "developer"],
    ["ai pair programmer", "code completion", "agent"]),
  ref("replicate", "Replicate", "growth", "ai", "aurora-dark", "developer-product",
    ["models", "api", "inference"],
    ["run models", "api", "machine learning deployment"]),
  ref("scale-ai", "Scale AI", "enterprise", "ai", "cobalt-enterprise", "enterprise-trust",
    ["data", "labeling", "enterprise"],
    ["training data", "annotation", "rlhf", "enterprise ai"])
];

// ── Creative, design & no-code ──────────────────────────────────────────────
const CREATIVE_REFS = [
  ref("figma", "Figma", "iconic", "creative-tools", "citrus-creative", "landing-bento",
    ["design", "collaboration", "colorful"],
    ["interface design", "prototyping", "design system", "collaboration"]),
  ref("framer", "Framer", "iconic", "creative-tools", "obsidian-lux", "landing-bento",
    ["design", "motion", "expressive", "no-code"],
    ["website builder", "motion design", "no-code", "publish"]),
  ref("webflow", "Webflow", "enterprise", "creative-tools", "obsidian-lux", "landing-bento",
    ["no-code", "design", "creative"],
    ["visual development", "cms", "hosting", "interactions"]),
  ref("sketch", "Sketch", "growth", "creative-tools", "citrus-creative", "landing-classic",
    ["design", "mac", "ui"],
    ["ui design", "symbols", "prototyping"]),
  ref("invision", "InVision", "enterprise", "creative-tools", "coral-marketing", "landing-classic",
    ["prototype", "design", "collaboration"],
    ["prototyping", "design collaboration", "handoff"]),
  ref("adobe", "Adobe", "fortune500", "creative-tools", "obsidian-lux", "landing-split",
    ["creative cloud", "design", "enterprise"],
    ["photoshop", "illustrator", "creative suite", "enterprise"]),
  ref("behance", "Behance", "growth", "creative-tools", "obsidian-lux", "landing-bento",
    ["portfolio", "creative", "showcase"],
    ["creative portfolio", "projects", "hire designers"]),
  ref("dribbble", "Dribbble", "growth", "creative-tools", "citrus-creative", "landing-bento",
    ["design", "community", "shots"],
    ["design community", "inspiration", "hire designers"]),
  ref("spline", "Spline", "growth", "creative-tools", "obsidian-lux", "landing-bento",
    ["3d", "design", "interactive"],
    ["3d design", "web 3d", "interactive scenes"]),
  ref("rive", "Rive", "growth", "creative-tools", "citrus-creative", "landing-bento",
    ["animation", "interactive", "motion"],
    ["real-time animation", "interactive graphics", "state machines"]),
  ref("pitch", "Pitch", "growth", "creative-tools", "citrus-creative", "landing-split",
    ["presentations", "collaboration", "slides"],
    ["presentation software", "deck design", "collaboration"]),
  ref("arc", "Arc Browser", "growth", "creative-tools", "citrus-creative", "landing-bento",
    ["browser", "design", "consumer"],
    ["web browser", "spaces", "design forward"]),
  ref("superhuman", "Superhuman", "growth", "saas", "monolith-mono", "minimal-showcase",
    ["email", "premium", "speed"],
    ["email client", "fast inbox", "keyboard shortcuts"]),
  ref("craft", "Craft", "growth", "saas", "atelier-warm", "editorial-story",
    ["docs", "notes", "beautiful"],
    ["document editor", "notes", "publishing"])
];

// ── Commerce & retail ─────────────────────────────────────────────────────────
const COMMERCE_REFS = [
  ref("shopify", "Shopify", "fortune500", "commerce", "meridian-light", "landing-split",
    ["ecommerce", "merchant", "green"],
    ["online store", "commerce platform", "checkout", "pos"]),
  ref("amazon", "Amazon", "fortune500", "commerce", "meridian-light", "landing-classic",
    ["marketplace", "retail", "consumer"],
    ["marketplace", "prime", "fulfillment", "aws"]),
  ref("etsy", "Etsy", "enterprise", "commerce", "atelier-warm", "editorial-story",
    ["handmade", "marketplace", "creative"],
    ["handmade marketplace", "crafts", "independent sellers"]),
  ref("stripe-commerce", "Stripe Commerce", "iconic", "commerce", "meridian-light", "landing-split",
    ["checkout", "payments", "commerce"],
    ["checkout", "payment links", "subscriptions"]),
  ref("bigcommerce", "BigCommerce", "enterprise", "commerce", "meridian-light", "enterprise-trust",
    ["ecommerce", "enterprise", "headless"],
    ["ecommerce platform", "headless commerce", "b2b"]),
  ref("squarespace", "Squarespace", "enterprise", "commerce", "monolith-mono", "minimal-showcase",
    ["website builder", "templates", "premium"],
    ["website builder", "templates", "domains", "commerce"]),
  ref("wix", "Wix", "enterprise", "commerce", "coral-marketing", "landing-bento",
    ["website builder", "no-code", "templates"],
    ["website builder", "drag and drop", "templates"]),
  ref("glossier", "Glossier", "growth", "commerce", "rose-health", "editorial-story",
    ["beauty", "d2c", "brand"],
    ["skincare", "beauty brand", "direct to consumer"]),
  ref("allbirds", "Allbirds", "growth", "commerce", "verdant-editorial", "editorial-story",
    ["sustainable", "footwear", "d2c"],
    ["sustainable shoes", "comfort", "materials"]),
  ref("nike", "Nike", "fortune500", "commerce", "monolith-mono", "minimal-showcase",
    ["sportswear", "premium", "bold"],
    ["athletic wear", "sneakers", "sport", "innovation"]),
  ref("apple-store", "Apple Store", "fortune500", "hardware", "monolith-mono", "minimal-showcase",
    ["premium", "hardware", "minimal"],
    ["devices", "iphone", "mac", "premium retail"]),
  ref("tesla", "Tesla", "fortune500", "hardware", "monolith-mono", "minimal-showcase",
    ["ev", "automotive", "premium"],
    ["electric vehicles", "energy", "autopilot", "sustainable"])
];

// ── Enterprise & B2B ──────────────────────────────────────────────────────────
const ENTERPRISE_REFS = [
  ref("databricks", "Databricks", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["data", "enterprise", "lakehouse"],
    ["data lakehouse", "spark", "ml platform", "analytics"]),
  ref("snowflake", "Snowflake", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["data cloud", "warehouse", "enterprise"],
    ["data warehouse", "cloud analytics", "sql"]),
  ref("palantir", "Palantir", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["defense", "data", "enterprise"],
    ["data integration", "government", "enterprise analytics"]),
  ref("servicenow", "ServiceNow", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["itsm", "workflow", "enterprise"],
    ["workflow automation", "itsm", "enterprise service"]),
  ref("workday", "Workday", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["hr", "finance", "enterprise"],
    ["hr software", "financial management", "planning"]),
  ref("okta", "Okta", "enterprise", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["identity", "sso", "security"],
    ["identity management", "sso", "authentication", "workforce"]),
  ref("crowdstrike", "CrowdStrike", "enterprise", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["security", "endpoint", "enterprise"],
    ["endpoint security", "threat detection", "falcon"]),
  ref("palo-alto", "Palo Alto Networks", "fortune500", "enterprise", "cobalt-enterprise", "enterprise-trust",
    ["security", "firewall", "enterprise"],
    ["cybersecurity", "network security", "cloud security"]),
  ref("mongodb", "MongoDB", "enterprise", "developer-tools", "signal-green", "enterprise-trust",
    ["database", "document", "enterprise"],
    ["document database", "atlas", "developer data platform"]),
  ref("elastic", "Elastic", "enterprise", "developer-tools", "cobalt-enterprise", "enterprise-trust",
    ["search", "observability", "enterprise"],
    ["elasticsearch", "kibana", "log analytics", "search"]),
  ref("twilio", "Twilio", "enterprise", "developer-tools", "meridian-light", "developer-product",
    ["communications", "api", "sms"],
    ["sms", "voice", "video api", "customer engagement"]),
  ref("segment", "Segment", "enterprise", "marketing", "cobalt-enterprise", "enterprise-trust",
    ["cdp", "analytics", "data"],
    ["customer data platform", "event tracking", "integrations"]),
  ref("amplitude", "Amplitude", "enterprise", "marketing", "halcyon-blue", "saas-pricing",
    ["product analytics", "growth"],
    ["product analytics", "behavioral data", "experimentation"]),
  ref("mixpanel", "Mixpanel", "enterprise", "marketing", "coral-marketing", "saas-pricing",
    ["analytics", "product", "funnels"],
    ["product analytics", "funnels", "retention"]),
  ref("gong", "Gong", "enterprise", "saas", "cobalt-enterprise", "enterprise-trust",
    ["revenue intelligence", "sales"],
    ["conversation intelligence", "revenue", "coaching"]),
  ref("rippling", "Rippling", "enterprise", "saas", "cobalt-enterprise", "enterprise-trust",
    ["hr", "it", "payroll"],
    ["hr platform", "device management", "payroll", "apps"])
];

// ── Media, entertainment & gaming ───────────────────────────────────────────
const MEDIA_REFS = [
  ref("spotify", "Spotify", "fortune500", "media", "signal-green", "landing-classic",
    ["music", "dark", "bold"],
    ["music streaming", "podcasts", "playlists", "audio"]),
  ref("netflix", "Netflix", "fortune500", "media", "ember-gaming", "landing-classic",
    ["streaming", "entertainment", "video"],
    ["video streaming", "movies", "series", "originals"]),
  ref("disney-plus", "Disney+", "fortune500", "media", "obsidian-lux", "landing-classic",
    ["streaming", "entertainment", "family"],
    ["streaming service", "movies", "marvel", "family"]),
  ref("youtube", "YouTube", "fortune500", "media", "ember-gaming", "landing-classic",
    ["video", "creator", "platform"],
    ["video platform", "creators", "streaming", "ads"]),
  ref("twitch", "Twitch", "enterprise", "media", "ember-gaming", "landing-bento",
    ["live streaming", "gaming", "community"],
    ["live streaming", "gaming", "creators", "chat"]),
  ref("discord", "Discord", "iconic", "social", "obsidian-lux", "landing-bento",
    ["community", "gaming", "purple"],
    ["voice chat", "community servers", "gaming", "social"]),
  ref("epic-games", "Epic Games", "enterprise", "gaming", "ember-gaming", "landing-bento",
    ["gaming", "3d", "bold", "unreal"],
    ["game engine", "fortnite", "unreal engine", "store"]),
  ref("riot", "Riot Games", "enterprise", "gaming", "ember-gaming", "landing-bento",
    ["gaming", "esports", "bold"],
    ["league of legends", "valorant", "esports", "games"]),
  ref("steam", "Steam", "enterprise", "gaming", "aurora-dark", "landing-classic",
    ["pc gaming", "store", "community"],
    ["game store", "pc gaming", "workshop", "community"]),
  ref("nyt", "The New York Times", "fortune500", "media", "verdant-editorial", "editorial-story",
    ["news", "editorial", "journalism"],
    ["news", "journalism", "subscription", "reporting"]),
  ref("substack", "Substack", "growth", "media", "verdant-editorial", "editorial-story",
    ["newsletter", "creator", "writing"],
    ["newsletter platform", "paid subscriptions", "writers"]),
  ref("medium", "Medium", "growth", "media", "verdant-editorial", "editorial-story",
    ["blog", "publishing", "reading"],
    ["publishing platform", "articles", "membership"]),
  ref("kinfolk", "Kinfolk", "iconic", "media", "verdant-editorial", "editorial-story",
    ["editorial", "lifestyle", "serif"],
    ["lifestyle magazine", "slow living", "design culture"]),
  ref("pitchfork", "Pitchfork", "growth", "media", "monolith-mono", "editorial-story",
    ["music", "reviews", "editorial"],
    ["music reviews", "culture", "editorial"])
];

// ── Health, wellness & travel ─────────────────────────────────────────────────
const LIFESTYLE_REFS = [
  ref("headspace", "Headspace", "enterprise", "health", "rose-health", "landing-classic",
    ["wellness", "meditation", "warm"],
    ["meditation", "mindfulness", "sleep", "mental health"]),
  ref("calm", "Calm", "enterprise", "health", "rose-health", "landing-classic",
    ["meditation", "sleep", "wellness"],
    ["sleep stories", "meditation", "relaxation"]),
  ref("peloton", "Peloton", "enterprise", "health", "monolith-mono", "landing-split",
    ["fitness", "premium", "hardware"],
    ["connected fitness", "cycling", "classes", "community"]),
  ref("whoop", "WHOOP", "growth", "health", "monolith-mono", "minimal-showcase",
    ["wearable", "performance", "data"],
    ["fitness tracker", "recovery", "strain", "sleep"]),
  ref("oura", "Oura", "growth", "health", "monolith-mono", "minimal-showcase",
    ["ring", "sleep", "health"],
    ["smart ring", "sleep tracking", "readiness"]),
  ref("airbnb", "Airbnb", "fortune500", "travel", "sand-travel", "landing-bento",
    ["travel", "warm", "consumer", "host"],
    ["vacation rental", "hosts", "experiences", "booking"]),
  ref("booking", "Booking.com", "fortune500", "travel", "halcyon-blue", "landing-classic",
    ["hotels", "travel", "booking"],
    ["hotel booking", "accommodations", "travel deals"]),
  ref("expedia", "Expedia", "fortune500", "travel", "sand-travel", "landing-classic",
    ["travel", "flights", "packages"],
    ["travel booking", "flights", "hotels", "packages"]),
  ref("kayak", "Kayak", "enterprise", "travel", "halcyon-blue", "landing-split",
    ["travel search", "flights", "compare"],
    ["travel search", "price compare", "flights", "hotels"]),
  ref("patagonia", "Patagonia", "iconic", "nonprofit", "verdant-editorial", "editorial-story",
    ["sustainability", "editorial", "outdoor"],
    ["outdoor gear", "sustainability", "activism", "environment"]),
  ref("nike-training", "Nike Training Club", "fortune500", "health", "monolith-mono", "landing-split",
    ["fitness", "training", "app"],
    ["workout app", "training plans", "fitness"])
];

// ── Legal, education & misc frontier ────────────────────────────────────────
const OTHER_REFS = [
  ref("harvey", "Harvey", "growth", "legal", "slate-legal", "enterprise-trust",
    ["legal ai", "law firm", "enterprise"],
    ["legal ai", "contract review", "research", "law firms"]),
  ref("ironclad", "Ironclad", "enterprise", "legal", "slate-legal", "enterprise-trust",
    ["clm", "contracts", "legal ops"],
    ["contract lifecycle", "legal workflow", "clm"]),
  ref("coursera", "Coursera", "enterprise", "education", "halcyon-blue", "landing-classic",
    ["courses", "learning", "certificates"],
    ["online courses", "degrees", "certificates", "learning"]),
  ref("duolingo", "Duolingo", "fortune500", "education", "signal-green", "landing-bento",
    ["language", "gamified", "consumer"],
    ["language learning", "gamification", "lessons"]),
  ref("khan-academy", "Khan Academy", "nonprofit", "education", "halcyon-blue", "landing-classic",
    ["nonprofit", "learning", "free"],
    ["free education", "math", "science", "courses"]),
  ref("vercel-ai", "Vercel AI SDK", "growth", "ai", "aurora-dark", "developer-product",
    ["ai sdk", "streaming", "developer"],
    ["ai sdk", "streaming ui", "llm apps", "react"]),
  ref("langchain", "LangChain", "growth", "ai", "aurora-dark", "developer-product",
    ["agents", "llm", "framework"],
    ["llm framework", "agents", "chains", "tools"]),
  ref("vercel-geist", "Vercel Geist", "iconic", "developer-tools", "monolith-mono", "minimal-showcase",
    ["design system", "minimal", "geist"],
    ["design system", "components", "typography"]),
  ref("shadcn", "shadcn/ui", "iconic", "developer-tools", "monolith-mono", "developer-product",
    ["components", "radix", "tailwind"],
    ["ui components", "copy paste", "accessible", "tailwind"]),
  ref("radix", "Radix UI", "growth", "developer-tools", "aurora-dark", "developer-product",
    ["primitives", "accessible", "react"],
    ["ui primitives", "accessibility", "unstyled components"]),
  ref("magic-ui", "Magic UI", "startup", "developer-tools", "aurora-dark", "landing-bento",
    ["animated", "components", "marketing"],
    ["animated components", "landing page", "marketing ui"]),
  ref("aceternity", "Aceternity UI", "startup", "developer-tools", "obsidian-lux", "landing-bento",
    ["animated", "modern", "effects"],
    ["animated ui", "modern effects", "tailwind components"])
];

export const UI_REFERENCE_CORPUS = [
  ...DEVELOPER_REFS,
  ...FINTECH_REFS,
  ...SAAS_REFS,
  ...AI_REFS,
  ...CREATIVE_REFS,
  ...COMMERCE_REFS,
  ...ENTERPRISE_REFS,
  ...MEDIA_REFS,
  ...LIFESTYLE_REFS,
  ...OTHER_REFS
];

// Back-compat alias for catalog.js matchReferenceSites
export const REFERENCE_SITES = UI_REFERENCE_CORPUS.map((entry) => ({
  id: entry.id,
  name: entry.name,
  industry: entry.industry,
  profileHint: entry.profileHint,
  tags: entry.tags
}));

export function corpusSummary() {
  const byTier = {};
  const byIndustry = {};
  for (const entry of UI_REFERENCE_CORPUS) {
    byTier[entry.tier] = (byTier[entry.tier] ?? 0) + 1;
    byIndustry[entry.industry] = (byIndustry[entry.industry] ?? 0) + 1;
  }
  return {
    references: UI_REFERENCE_CORPUS.length,
    tiers: CORPUS_TIERS.length,
    industries: Object.keys(INDUSTRY_VOCABULARY).length,
    byTier,
    byIndustry
  };
}
