import { writeFile } from "node:fs/promises";
import path from "node:path";

export function buildAgentRules({ projectName, grammar, componentImports = {} }) {
  const tokenLines = Object.entries(grammar.tokens ?? {})
    .sort(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `- \`--${name}\`: ${value}`);

  const componentLines = Object.entries(componentImports)
    .map(([name, importPath]) => `- \`${name}\` → \`${importPath}\``);

  const agentsMd = `# ${projectName} — Agent Design Contract

morph generated this file to stop coding agents from drifting off the product design system.

## Locked tokens

Do not invent new colors, spacing, radii, or type sizes. Use these CSS variables:

${tokenLines.join("\n")}

## Component grammar

${componentLines.length ? componentLines.join("\n") : "- Reuse shared components from the product library instead of raw HTML controls."}

## Hard rules

1. Never hardcode hex colors in JSX, Tailwind arbitrary values, or inline styles.
2. Never use raw \`<button>\` when a shared Button component exists.
3. Never remove focus-visible states without replacing them with the product focus token.
4. Snap spacing to the token scale — no one-off \`px\` guesses.
5. Run \`morph verify --json\` before opening a PR.

## Repair loop

\`\`\`bash
morph verify --json
morph repair --apply
morph verify --json
\`\`\`
`;

  const cursorRule = `---
description: Design system guardrails for ${projectName}. morph locks tokens and blocks agent drift.
globs:
  - "src/**/*.{tsx,jsx,css,html}"
alwaysApply: true
---

# Design system dictatorship (${projectName})

You may write product logic. You may **not** invent visual language.

## Token law

${tokenLines.slice(0, 12).join("\n")}

## Component law

${componentLines.length ? componentLines.join("\n") : "- Use shared product components instead of reimplementing controls."}

## Forbidden

- Hardcoded hex (\`#RRGGBB\`) or Tailwind palette colors (\`bg-red-500\`)
- Arbitrary spacing/radius (\`p-[18px]\`, \`rounded-[28px]\`) outside the token scale
- Raw \`<button>\` when \`Button\` exists
- \`focus:outline-none\` without a \`focus-visible\` replacement

## Before merge

Run \`morph loop --apply\` and ensure the report passes.
`;

  const designSystemMd = `# DESIGN_SYSTEM.md

> Auto-generated by morph from product tokens. Treat as ground truth for all UI work.

## Colors

${Object.entries(grammar.colors ?? {}).map(([name, value]) => `- ${name}: ${value}`).join("\n")}

## Spacing

${Object.entries(grammar.spacing ?? {}).map(([name, value]) => `- ${name}: ${value}`).join("\n")}

## Radius

${Object.entries(grammar.radius ?? {}).map(([name, value]) => `- ${name}: ${value}`).join("\n")}

## Typography

${Object.entries(grammar.fontSize ?? {}).map(([name, value]) => `- ${name}: ${value}`).join("\n")}

## Agent instruction

Before writing UI, read this file. Every color, spacing, radius, and type decision must trace back here.
`;

  return { agentsMd, cursorRule, designSystemMd };
}

export async function writeAgentRules(targetDir, payload) {
  const created = [];
  const agentsPath = path.join(targetDir, "AGENTS.md");
  const designPath = path.join(targetDir, "DESIGN_SYSTEM.md");
  const cursorDir = path.join(targetDir, ".cursor", "rules");
  const cursorPath = path.join(cursorDir, "morph-design-system.mdc");

  await writeFile(agentsPath, payload.agentsMd);
  created.push("AGENTS.md");

  await writeFile(designPath, payload.designSystemMd);
  created.push("DESIGN_SYSTEM.md");

  const { mkdir } = await import("node:fs/promises");
  await mkdir(cursorDir, { recursive: true });
  await writeFile(cursorPath, payload.cursorRule);
  created.push(path.join(".cursor", "rules", "morph-design-system.mdc"));

  return created;
}
